layout_spectrum: 0.04617417
typography_spectrum: 0.4907535
color:
  saturation: 0.4860079
  lightness: 0.04321186
  brandStrength: 0.7288247
  rhythmicContrast: 0.4181391
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
name: franfran
